### ISSUE TITLE
ingo-library: version bump to 1.026

### ISSUE THREAD

**Issue by Coacher** [vim-scraper/vim-scraper#89]
Hello.

Current version from vim-scripts/ is 1.024: https://github.com/vim-scripts/ingo-library/commit/558132e2221db3af26dc2f2c6756d092d48a459f
Current version from www.vim.org is 1.026: http://www.vim.org/scripts/script.php?script_id=4433

1.026 was released more than a month ago.

Please bump.

**Comment by bronson** [comment]
Hi, sorry.  It looks like nobody is interested in maintaining the scraper anymore.  We're figuring out the best way to wind this project down.

**Comment by Coacher** [comment]
This is sad news. Do you know a painless way to install vimballs? Manual downloading them is a pain :)

**Comment by Coacher** [comment]
Fixed by tracking changes in a local git repo manually.

**Comment by bronson** [comment]
Right on.

I suppose we've discovered the way to wind the project down: do nothing, and let github continue hosting the scraped content until they tire of it.  Sigh!
